version: 2

models:
  - name: projecoes2_table # tabela do banco de dados
    columns:
      - name: year
      - name: local
      - name: pop_t
      - name: pop_h
      - name: pop_m
      - name: e0_t
      - name: e60_t