version: 2

sources:
  - name: projecoes2_banco # banco de dados
    description: This is a replica of the MySQL database used by our client.
    tables:
      - name: projecoes2_table # tabela do banco de dados
        description: Table containing population projections by year..
        columns:
          - name: ano
            description: Primary key of the projecoes2_table.
            tests:
              - unique
              - not_null
          - name: local
            description: Location of population projection.
          - name: pop_t
            description: Projected total population.
          - name: pop_h
            description: Projected male population.
          - name: pop_m
            description: Projected female population.
          - name: e0_t
            description: Projection for the age group 0-20 years.
          - name: e60_t
            description: Projection for the age group 60+ years.